export default [
  {
    username: "",
    password: "12345678",
    last_login: "",
    is_superuser: "",
    first_name: "",
    last_name: "",
    email: "kaptainCS3@gmail.com",
    is_staff: "",
    is_active: "",
    date_joined: "",
    groups: [],
    user_permissions: [],
  },
  {
    username: "",
    password: "12345678",
    last_login: "",
    is_superuser: "",
    first_name: "",
    last_name: "",
    email: "madadjo@gmail.com",
    is_staff: "",
    is_active: "",
    date_joined: "",
    groups: [],
    user_permissions: [],
  },
  {
    username: "",
    password: "12345678",
    last_login: "",
    is_superuser: "",
    first_name: "",
    last_name: "",
    email: "thierryjr@gmail.com",
    is_staff: "",
    is_active: "",
    date_joined: "",
    groups: [],
    user_permissions: [],
  },
];
