export default [
  {
    id: 1,
    img: "/assets/food_features/image1.jpg",
    title: "Lofts",
    discount: "30k",
    type: "Bakery",
    distance: "0.3 km",
  },
  {
    id: 2,
    img: "/assets/food_features/image2.jpg",
    title: "Queens Arcard",
    discount: "20k",
    type: "Western Food",
    distance: "0.6 km",
  },
  {
    id: 3,
    img: "/assets/food_features/image3.jpg",
    title: "Scoop That",
    discount: "15k",
    type: "Snacks and Beverages",
    distance: "0.3 km",
  },
  {
    id: 4,
    img: "/assets/food_features/image4.jpg",
    title: "This is Holland",
    discount: "20k",
    type: "Bakery",
    distance: "0.3 km",
  },
  {
    id: 5,
    img: "/assets/food_features/image5.jpg",
    title: "Day 2 Night",
    discount: "30k",
    type: "Rice",
    distance: "0.3 km",
  },
  {
    id: 6,
    img: "/assets/food_features/image6.jpg",
    title: "Cake Spade",
    discount: "30k",
    type: "Bakery and sweets",
    distance: "0.3 km",
  },
];
